apiVersion: batch/v1
kind: CronJob
metadata:
  name: gtfd-cronjob
  labels:
    app: gtfd
spec:
  schedule: "01 1 * * *"
  #schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: gtfd
            image: mcguinnessa/get-titles-from-disk:latest
            imagePullPolicy: IfNotPresent
            env:
            - name: MONGODB_USER
              value: film_mgr
            - name: MONGODB_PASS
              value: paramount
            - name: MONGODB_HOST
              value: "192.168.0.116"
            - name: MONGODB_PORT
              value: "30164"
            - name: SMB_USER
              value: "Alex"
            - name: SMB_PASS
              value: "Gomez"
            - name: SMB_HOST
              value: "gerrard.home.lan"
          restartPolicy: Never 



# Use the localhost:32000 path to use image from registry service
# e.g.  image: localhost:32000/hello-app:v3
#        ports:
#        - containerPort: 3000
